### ISSUE TITLE
Using consistent terminology for distribution / partitioning in our FAQs

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#101]
In our documentation, we use "hash distribution" to refer to distributing Citus tables using the hashing method. In our FAQ, we refer to it as "hash partitioning".  Could we unify our terminology across these sections?

@samay-sharma -- I know you worked on unifying some of these terms when you worked on the documentation. Could you share those terms with us?

**Comment by begriffs** [comment]
Random collection of thoughts as I review the terminology in the docs.

* Note this standardization might extend to terms such as "repartition join" as well. If we *distribute* tables by *distribution* columns, shouldn't these joins be called "redistribution joins?"
* A number of places in the docs say "partitions an incoming query into fragment queries." To me "partition ... into fragments" sounds more natural than "distribute ... into fragments" since partitioning connotes discontinuous pieces whereas distribution applies to *mass nouns* such as water. Maybe "distribute ... across shards" resolves it.
* The term partition agrees with the regular Postgres meaning, but also overloads it between local and distributed partitioning.
* However the term is present in our API: `partition_buffer_size`, `pg_dist_partition`
* The term distributed occurs more often

**Comment by begriffs** [comment]
Noting there are still many places where we use the term partition. https://docs.citusdata.com/en/v7.3/search.html?q=partition&check_keywords=yes&area=default

**Comment by jonels-msft** [comment]
The situation looks better in the 8.3 docs, where we talk about partitioning only for window functions and real postgres partitioning used in time-series data. There is a little nonstandard usage in our FAQ, but not too big of a deal.
