### ISSUE TITLE
Add FAQ about having to run per-server commands on all nodes

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus_docs#150]
Citus does not automatically propagate commands like `CREATE DATABASE, CREATE EXTENSION, CREATE TYPE, CREATE FUNCTION etc` to the workers if run on the master.

If the user runs these commands on the workers, then these constructs are supported. However, at times users run these commands only on the master and hence get the impression that Citus doesn't support the above.

We should document this and guide the users to run these commands on all nodes.

**Comment by umurc** [comment]
+1

**Comment by begriffs** [comment]
I'm deprioritizing this issue for the moment in order to document the multi-tenant workflow.

**Comment by begriffs** [comment]
Based on Samay's comment and my searching the code it appears that these commands are not propagated:

* ALTER TABLE ALL IN TABLESPACE
* CREATE DATABASE
* CREATE ROLE/USER
* ALTER ... SET SCHEMA
* CREATE VIEW
* CREATE EXTENSION
* CREATE TYPE
* CREATE FUNCTION

But maybe it's better to construct a whitelist of propagated commands instead?

**Comment by HackerMD** [comment]
Are there plans to propagate these command in the future?

Having to run CREATE DATABASE (and CREATE EXTENSION) on each worker node becomes problematic when an application needs to create databases dynamically. The application then needs to keep track of worker nodes and connect to each of them individually. In my opinion this should be handled by the master rather than the application. From an architectural point of view, I would even argue that users shouldn't be able to connect to worker nodes directly.

**Comment by mjgp2** [comment]
This is what we are currently having issues with, we need to create databases, schemas and roles dynamically and there is an issue here for us propagating the roles across nodes.

Is there a suggested workaround for carrying out quite simple DB management that needs executing on each node?

**Comment by begriffs** [comment]
Let me know if this section gives you the answers you need:

https://docs.citusdata.com/en/v7.3/extra/query_propagation.html

**Comment by begriffs** [comment]
Also noting we have some details about the propagation of table modification - https://docs.citusdata.com/en/v7.3/dist_tables/ddl.html#modifying-tables - although adding an FAQ entry probably wouldn't hurt.
