### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus_docs#151]
The current README for the repository was written for an internal audience to act as a guide for building the docs from sphinx source. However, after we've open sourced the docs and changed the deployment process, the current content isn't very relevant.

We should update the readme content and it make it more up to date.

**Comment by begriffs** [comment]
What else do you think we should include? Could talk about the RTD branching/cherry-picking strategy, although we've been managing that pretty well by word of mouth.

**Comment by begriffs** [comment]
@samay-sharma just a ping about this, what do you have in mind? Maybe I could add a link to docs.citusdata.com saying this is the source for that site.

Otherwise the readme steps still seem to be correct. Only difference is that I usually run `sphinx-autobuild` rather than `sphinx-build` so that I can preview changes live locally.

**Comment by begriffs** [comment]
Actually I'm going to close this issue, but feel free to reopen if there are important changes for the readme.
