### ISSUE TITLE
Document colocate_with option of create_distributed_function UDF

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#226]

**Comment by metdos** [comment]
PR is merged for this. Here is the description of the feature:

**1- Default option:**

This is the current behavior of the distributed colocated table creation. If there is a collocation group with the same configuration, use it. Otherwise, create a new colocation group.

i. Provide colocate_with => 'default' 

``` sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'default');
```

ii. Or does not provide colocate_with at all and use 'default' as the default value.

``` sql
select create_distributed_table('orders', 'o_orderkey');
```

**2- Colocate with a specific table**

Colocate with the given table. If not possible, error out.

``` sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'lineitem');
```

**3- Create a new colocation group**

Create a new colocation group id, but don't add a line to pg_dist_colocation.

``` sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'none');
```

**Comment by begriffs** [comment]
## Why are we implementing it? (sales eng)

* Makes colocation explicit in the API, reinforcing that it is important for performance.
* Ensures colocation even for situations where a worker failure prevents shard placement and makes two tables seem to have a different shard counts.
* Allows foreign key constraints to survive shard rebalancing
   ```sql
   select create_distributed_table('stores', 'id');

   -- Good for initial co-location
   select create_distributed_table('orders', 'store_id');
   -- VS this one, better for the future
   select create_distributed_table('orders', 'store_id', colocate_with=>'stores');
   ```
* Colocation groups can be used to express that tables distributed by same type of columns using the same shard count should may *not* be related. This makes the rebalancer more efficient.

### What are the typical use cases?


## Communication goals (e.g. detailed howto vs orientation)

### Good locations for content in docs structure

* Document new parameter in `/reference/user_defined_functions.html`
* Add details about colocation groups to `/dist_tables/ddl.html#creating-and-distributing-tables`

## How does this work? (devs)

Enables users to override the default behavior inferred from distribution column type and shard count.

### Example sql

See Metin's comment above.

### Corner cases, gotchas

### Are there relevant blog posts or outside documentation about the concept/feature?

https://github.com/citusdata/citus/issues/695

### Link to relevant commits and regression tests if applicable

* https://github.com/citusdata/citus/blob/master/src/test/regress/sql/multi_colocation_utils.sql
