### ISSUE TITLE
Better docs on write throughputs Citus can handle

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#245]
## Why are we implementing it? (sales eng)
To elaborate on what throughputs citus can scale to.
Could show benchmarks(for both \COPY and INSERTS) related citus and MX.

### What are the typical use cases?
Mostly for communication purposes.

### Good locations for content in docs structure
A Blogpost.
Or **May be start section called Benchmarks, which possible benchmarks (SELECTS, INDEXES, DMLS, ROLL UPS etc)** @begriffs @sumedhpathak @samay-sharma : Any thoughts on this idea? Could chat in a separate thread.

**Comment by samay-sharma** [comment]
@saicitus : Adding context. (We chatted about this a bit with @ozgune and @umurc internally too.)

The main idea here was that currently we don't have content in documentation about what kinds of throughputs, scalability characteristics, numbers etc. people can expect with Citus. This includes more general stuff like node counts and data sizes and also specific items like write throughputs.

This question specifically came from one conversation where a user was concerned whether Citus could handle write throughputs of ~600-700 writes / second (he's currently at a much lower throughput) which we should comfortably be able to do. So, somehow calling this out in docs would be useful so that users can know what they can expect.

However, this does require some more thought regarding what and how to communicate. @sumedhpathak , @begriffs : Might be an item worth chatting about in our docs prioritization cycle.
