### ISSUE TITLE
SQL commands are not colorized

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#269]
SQL Commands are not colorized on the web but in my local computer I can see the commands colorized correctly with sphinx. It would be nice to see the colorized SQL snippets on the web as well.

**Comment by begriffs** [comment]
The majority of code is now colorized by the introduction of the new sphinx theme. Any code that lacks highlighting does so because its language is not specified in a handful of places. Checking syntax highlighting is a checklist item in the open PR for restructuring the main menu, so I'm closing this issue.
