### ISSUE TITLE
Inform users of mandatory need to run ALTER EXTENSION UPDATE on minor/major updates.

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#281]
## How does this work? (devs)

This comes from https://github.com/citusdata/citus/issues/907. Brian summarized the conversation there as:

* We add a fail-safe preventing you from running ALTER EXTENSION before you've restarted
* For minor releases we allow the user to restart and then ALTER at their leisure. (And restrict ourselves to the kinds of changes which allow such)
* For major releases we fail-safe and prevent the user from running any distributed queries until ALTER has been run.

### Link to relevant commits and regression tests if applicable

**Comment by sumedhpathak** [comment]
Edit: Modified the title a bit to reflect the issue a bit better.

**Comment by byucesoy** [comment]
## How does this work? (devs)

This comes from https://github.com/citusdata/citus/issues/907. Brian summarized the conversation there as:

Addition to Brian's summary,

For major version changes (e.g. from 6.1 to 6.2)
* If there is new version installed to the system, we force users to restart the servers so that new binaries 
will be loaded. Until that, we are not allowing to run any distributed queries and most non-distributed queries.
* If new binaries loaded but user did not run ALTER EXTENSION citus UPDATE, we also force user to run ALTER EXTENSION. Until that, we are not allowing to run any distributed queries and most non-distributed queries.
* When there is new version available, we do not allow running ALTER EXTENSION if user does not restart the server first.
* We also introduced read-only GUC variable named `citus.version`. It is useful to see running citus version.

For minor relases, we do not enforce anything.

### Example sql

### Corner cases, gotchas

Probably we do not want to document this, but we have a GUC variable called citus.enable_version_checks. Its default value is true, if you set it to false, we will not perform any of these version checks and Citus will try to run any given queries.

### Are there relevant blog posts or outside documentation about the concept/feature?

### Link to relevant commits and regression tests if applicable

**Comment by begriffs** [comment]
Thanks for the extra info, Burak. I think PR #314 covers it pretty well, although I don't mention citus.version or citus.enable_version_checks.
