### ISSUE TITLE
How to enable/disable triggers on distributed tables

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#284]
### Link to relevant commits and regression tests if applicable

**Comment by begriffs** [comment]
Associated with https://github.com/citusdata/citus/issues/1080

**Comment by begriffs** [comment]
Waiting on this issue until the 6.2 behavior is decided and implemented.

**Comment by begriffs** [comment]
@metdos now that this feature is merged can you fill in the details for documentation? Example sql, gotchas etc.

**Comment by metdos** [comment]
> @metdos now that this feature is merged can you fill in the details for documentation? Example sql, gotchas etc.

@begriffs, sorry I missed the documentation tag. Actually, there are not any gotchas other than we don't support creating triggers in a distributed manner so the user needs to go and create triggers on individual shards one by one by himself.

For this PR, the user can disable/enable all triggers on a distributed table - especially if the user created triggers by himself on worker nodes otherwise this is an impotent operation (we used to fail on this).

Example calls;
```sql
ALTER TABLE lineitem DISABLE TRIGGER ALL;
ALTER TABLE lineitem ENABLE TRIGGER ALL;
```

**Comment by lfittl** [comment]
When looking at this it might also be worth mentioning that this can be used to temporarily disable foreign keys, per https://www.postgresql.org/message-id/4EA2057F.3000002@ringerc.id.au

(this is the reason Rails uses it for tests - it disables triggers and then truncates the table, avoiding any foreign key checks)

**Comment by begriffs** [comment]
@lfittl considering closing this issue now that Citus can handle the standard way of enabling/disabling triggers. Any objection?

**Comment by lfittl** [comment]
@begriffs Sounds good!
