### ISSUE TITLE
How to specify correct roles for Cloud users

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#346]
## Why are we implementing it? (sales eng)

Organizations using Citus Cloud want to give different levels of access to different systems. We pass that responsibility to the Postgres roles underneath.

### What are the typical use cases?

The most common case is creating a user with read-only access for use by a web/reporting tool.

## Communication goals (e.g. detailed howto vs orientation)

Provide instructions for:
* add role through web interface
* psql in as the admin to customize role access

@lfittl are these the steps? Any other things to add about use cases?

### Good locations for content in docs structure

A new "Users and Security" section in Cloud

### Corner cases, gotchas

By default new users cannot access anything!

**Comment by lfittl** [comment]
@begriffs Thats basically it - with roles I would also mention how PostgreSQL's grants work, and the following gotcha:

* Any GRANT thats on a specific distributed table will be propagated to the data nodes
* GRANTs that are system-wide (e.g. for all tables in a schema) need to be applied individually to every data node. You can use Citus tools to do so

It might be worth including a specific example of how to setup a read-only user, since that is the most common use case.

**Comment by begriffs** [comment]
Thanks for the notes. Is it still true that new users cannot access anything? The placeholder text in this dialog box makes it look like the user will have read only access:

![screen shot 2017-04-20 at 12 40 34 pm](https://cloud.githubusercontent.com/assets/911911/25244517/b53c938c-25c6-11e7-9d05-1ec520d68cb7.png)

**Comment by lfittl** [comment]
@begriffs The place holder text is wrong in that regard. Once we have docs up I'll likely just link to them and update that text to say `my_user_name`

**Comment by begriffs** [comment]
(Closed by a PR)
