### ISSUE TITLE
Allow the top-level menu sections to be collapsible, so we can navigate the index easier.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#405]
- Make the Left Nav bar independently scrollable
- Allow the top-level sections to be collapsable, so we can navigate the index easier.

**Comment by begriffs** [comment]
https://github.com/citusdata/citus_docs/pull/416 ran into some trouble given the current theme styling. The PR is closed now, but contains useful comments for when we investigate changing either our theme or docs generation system.

**Comment by begriffs** [comment]
Renamed this since the menu redesign will take care of the independent scrolling aspect.

**Comment by begriffs** [comment]
There are two things that make this pretty difficult.

First, I thought I could override the menu markup to use a special html tag called `<summary>` for the open/close toggle. For instance:

<details>
<summary>Click me!</summary>
The fun stuff inside
</details>

```html
<!-- the code for the above -->
<details>
<summary>Click me!</summary>
The fun stuff inside
</details>
```

However the markup used within the menu is hard-coded [deep inside](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/environment/adapters/toctree.py#L71
) Sphinx, not in the theme.

Next, the open or closed status has to be tied to which url you're on. For instance if the user visits https://docs.citusdata.com/en/v7.3/get_started/concepts.html then the Get Started section needs to be opened by default. This state is managed with a combination of sphinx adding a "current" class to the open menu item markup, and javascript to [toggleCurrent](https://github.com/rtfd/sphinx_rtd_theme/blob/41ab3d2ecbe87f3875c42922a80778330ae8f021/js/theme.js#L189-L195) on navigation clicks.

To get collapsible top level items we'd have to do one of three things
1. Fork sphinx itself and change the markup for the menu. Not sure how to use a sphinx fork on RTD hosting  though. Also the changed markup would probably mess with existing javascript like `toggleCurrent`.
2. Add heavy javascript that works alongside the script from the theme to hide/show sections of the menu. Seems fragile and complicated.
3. Change the structure of each ReStructuredText section so that they all have one top-level header, and remove captions from the main menu. This would change the look of the menu however since those captions are brighter and slightly set apart from the menu items.

These options are all difficult, and imho don't seem worth it. A change this big would be reason to probably look at an entirely different docs system. (Unless there's another option that I overlooked.)

/cc @samay-sharma

**Comment by begriffs** [comment]
(From in-person discussion: Decided to do option 3)
