### ISSUE TITLE
HLL aggreagate steps are missing for distributed tables in Realtime Dashboards tutorial

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#433]
The Real Time Dashboards tutorial is aimed towards mostly single node Postgres. This causes confusion when users try these queries with distributed tables and see them fail.

Specifically the following HLL query won't work on distributed tables:
```
SELECT
  site_id, date_trunc('minute', ingest_time) as minute,
  hll_add_agg(hll_hash_text(ip_address)) AS distinct_ip_addresses
FROM http_request
WHERE date_trunc('minute', ingest_time) = date_trunc('minute', now())
GROUP BY site_id, minute;
```

We may consider distinguishing between what is distributed and what is non distributed.

**Comment by sumedhpathak** [comment]
What part is confusing or misleading? The dashboard example as I understand it isn't meant to be run only on single-node PostgreSQL. Is that query not supposed to be run on the master node?

**Comment by aamederen** [comment]
@sumedhpathak I also thought that the query I mentioned was supposed to be run on the master node on a distributed table. However, when run on a distributed table, the query errors out with `ERROR:  unsupported aggregate function hll_add_agg`. So either the tutorial is aimed towards single node postgres or we need to modify the query.

**Comment by sumedhpathak** [comment]
Ok. After going through the tutorial again, if one is just trying to run every query, then it is a bit confusing. The text indicates that a query like this should be used in the roll-up script. So its not meant to be run on the master.
@aamederen The title for this issue is very broad, given the issue reported. Could you please update this issue with a more specific title?

Also, in the future, providing some context on how we could fix this (or better yet opening up a PR) will be helpful. It helps us work on the issue without having to run through the full use-case guide to understand the issue again.

**Comment by sumedhpathak** [comment]
@aamederen ping on this one.

**Comment by ozgune** [comment]
@aamederen -- I think this particular step ([in your comment](https://github.com/citusdata/citus_docs/issues/433#issue-250296627)) was written before we had `INSERT INTO ... SELECT`.

We have two issues that capture these dated steps in our docs. #41 talks about better documenting HLL (HyperLogLog). #198 talks about updating our use case guide and providing up-to-date (and distributed steps).

Do you think this issue could be merged into one of those issues as a comment?
