### ISSUE TITLE
Subquery in where example is no longer accurate

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#485]
@ozgune  pointed out that in our workarounds section we have a [query](https://docs.citusdata.com/en/v7.0/reference/sql_workarounds.html#subqueries-in-where) that now works because the subquery returns values from the partition column which are fed into an `in` clause. We need to adjust the query to fail, by using a non-partition column. Think of a realistic example for this section.

**Comment by saicitus** [comment]
In addition to the above, we should make it more **explicit** that for multi-tenant workloads where all your queries are for a single tenant, you get full SQL coverage and the workarounds are not relevant.
We do have it captured in the docs that `Citus supports all SQL statements in the multi-tenant use-case.` But we need to make it more explicit just that users don't get the perception that citus doesn't support those features.
One idea for making this explicit is, for each work-around mention that this is not relevant for multi-tenant workloads where you shard on tenant_id and all your queries are for a single tenant. By this just before a user reads that workaround, he understands that it is not relevant for him because his queries are all for a single tenant.

**Comment by begriffs** [comment]
Our sql workarounds section is very small now and doesn't mention subqueries.
