### ISSUE TITLE
Document Cloud Followers feature

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#552]
We are now live with Followers on Cloud. There doesn't seem to be a ton of information on it. The Cloud 2.0 launch blog post has very basic bits of information: https://www.citusdata.com/blog/2017/11/16/citus-cloud-2-postgres-and-scale-without-compromise/.

We can try out the UI, and document steps.

**Comment by aamederen** [comment]
A few inputs on this:

- Follower clusters don't use streaming replication and fetch logs from S3 via wal-e, meaning zero load on the original cluster.
- Whenever a failover happens on the parent formation, the follower server will stop following, due to timeline changes. This includes scaling up (changing tunes), scaling out (adding more nodes), upgrades and failovers due to unavailabilities. Currently I am working on polishing this experience.

**Comment by sumedhpathak** [comment]
Also, add in FAQ: "Can I query read replicas"?
