### ISSUE TITLE
Upgrading Citus version through cloud GUI

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#661]
## Communication goals (e.g. detailed howto vs orientation)

We have a guide for [on prem upgrades](https://docs.citusdata.com/en/v7.3/admin_guide/upgrading_citus.html) but the process will be easier on Cloud. Add a guide when the feature is ready. Could note that it is currently done via a support ticket.

### Good locations for content in docs structure

New section in https://docs.citusdata.com/en/v7.3/cloud/manage.html

**Comment by begriffs** [comment]
Burak can advise.

**Comment by byucesoy** [comment]
Per our discussion, I'm adding my thought and comments here;

We deployed self service upgrades feature to cloud. We now allow users to upgrade their formations by themselves without opening a ticket. It is available for Citus internal org, so anyone from Citus can play with it, but at the moment it is hidden for almost all customers. We are planning to enable it for all customers when we have the documentation of this feature. We will probably put a link in the UI to the documentation page of this feature so that users can know more about the upgrade process before trying to upgrade. Here are some things, I think we should mention in the documentation;

- It is *strongly* recommended to try upgrading with a fork first. It would take some extra time but it could save them from potential downtime and minimize the risk of upgrading.
- To upgrade the formation, we will create new servers with requested PostgreSQL/Citus version and replay WAL to catch new servers to the existing servers. Downloading and replaying WAL segments would take long time depending on the data size. (speed of downloading and replaying WAL is ~100 GB per server per hour, but I'm not sure if it is OK to give an estimation since I saw multiple times WAL replaying took much longer than this estimation would suggest)
- After the new servers are ready, we will automaticaly redirect traffic to the new servers. During the redirection there may be couple minutes of downtime. We will wait until the maintenance window to redirect traffic, if it is set.
- If customer has HA enabled, we will automatically create new standby servers.
- If customes has follower formations, they will not get new updates. After upgrade operation is completed, customer should destroy and re-create the follower formations (we will probably automatically destroy followers soon but customer will still need to automaticaly re-create them.
